version: '{build}'
skip_tags: true
skip_commits:
  files:
    - Change.txt
    - '*.rst'
    - .travis.yml
    - 'docs/*'
    - 'craftwar.obs_updater/*'
    - '.*'
image: Visual Studio 2017
init:
  - ps: if (0) { iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) } #rdp debug
environment:
  CEF_VERSION: 3.3440.1805.gbe070f9
  vc_inc_arch: AVX2
  D3D12_HOOK: false

  matrix:
    - favor_arch: AMD64
    - favor_arch: INTEL64
    - favor_arch: blend
      vc_inc_arch: SSE2
      D3D12_HOOK: true
# setting rdp passoword never works
#  APPVEYOR_RDP_PASSWORD:
#    secure: K6XkhLVN7PZDnWWtrTKYneDPMS7FgBFYYe1xuU2s8js=

matrix:
  fast_finish: true
install:
#  - git submodule update --init --recursive --remote plugins\win-dshow
  - C:\projects\obs-studio\CI\craftwar\submodule.cmd
  - git fetch --tags --prune https://github.com/obsproject/obs-studio.git # get tags from official obs
  - if exist dependencies2017.zip (curl -kLO https://obsproject.com/downloads/dependencies2017.zip -f --retry 5 -z dependencies2017.zip) else (curl -kLO https://obsproject.com/downloads/dependencies2017.zip -f --retry 5 -C -)
  #- set VCdeps_url=https://ci.appveyor.com/api/projects/craftwar_appveyor/obs-deps/artifacts/VCdeps-blend.7z?job=Environment%3A%20favor_arch%3D%favor_arch%
  - set VCdeps_url=https://github.com/craftwar/obs-deps/releases/download/git/VCdeps-%favor_arch%.7z
  - if exist VCdeps-%favor_arch%.7z (curl -kLo VCdeps-%favor_arch%.7z %VCdeps_url% -f --retry 5 -z VCdeps-%favor_arch%.7z) else (curl -kLo VCdeps-%favor_arch%.7z %VCdeps_url% -f --retry 5 -C -)

# for 32bit cmake run
  - 7z x dependencies2017.zip -oold_dep
  - 7z x VCdeps-%favor_arch%.7z -odependencies2017
# update nvenc related headers
  - move /Y dependencies2017\Win64\include\ffnvcodec\*.h "C:\projects\\%APPVEYOR_PROJECT_NAME%\plugins\obs-ffmpeg"
  - set DepsPath32=%CD%\old_dep\win32
  - set DepsPath64=%CD%\dependencies2017\win64
#  - set curlPath=%APPVEYOR_BUILD_FOLDER%\old_dep\win64\include\
  - set QTDIR32=C:\Qt\latest\msvc2015
  - set QTDIR64=C:\Qt\latest\msvc2017_64
  - set build_config=Release
#  -Zc:inline is disabled when -GL is on
  - set cl_options=-MP -Oi -arch:%vc_inc_arch% -Gw -Gy -GL -GS- -favor:%favor_arch% -Zc:__cplusplus
#vcpkg
  - vcpkg remove --outdated --recurse
# /MP /Oi is default in vcpkg
  - set VCPKG_LINKER_FLAGS=/LTCG
  - set VCPKG_C_FLAGS=/arch:%vc_inc_arch% /Gw /Gy /GL /GS- /favor:%favor_arch% /Zc:__cplusplus
  - set VCPKG_CXX_FLAGS=%VCPKG_C_FLAGS%
  - '"C:\Program Files\Git\usr\bin\sed.exe" -i "s/CRT_LINKAGE static/CRT_LINKAGE dynamic/" /c/tools/vcpkg/triplets/x64-windows-static.cmake' #patch to dynamic crt
  - echo set(VCPKG_BUILD_TYPE release) >> C:\tools\vcpkg\triplets\x64-windows-static.cmake
  - if NOT "%favor_arch%"=="blend" vcpkg install jansson:x64-windows-static
  - vcpkg install zlib:x64-windows
  - copy /Y dependencies2017\win64\lib\zlib.lib C:\tools\vcpkg\installed\x64-windows\lib\
  - copy /Y dependencies2017\win64\bin\zlib.dll C:\tools\vcpkg\installed\x64-windows\bin\
  - copy /Y dependencies2017\win64\include\z* C:\tools\vcpkg\installed\x64-windows\include\
#  - echo set(VCPKG_BUILD_TYPE release) >> C:\tools\vcpkg\triplets\x64-windows.cmake # bug curl can't build
  - echo set(CURL_USE_WINSSL on) >> C:\tools\vcpkg\triplets\x64-windows.cmake
  - vcpkg install curl:x64-windows
  - set curlPath=C:\tools\vcpkg\installed\x64-windows\include

build_script:
  - mkdir build build32 build64
  - cd ./build64
#  - cmake -E env CFLAGS="%cl_options%"  CXXFLAGS="%cl_options%" LDFLAGS="-LTCG" cmake -G "Visual Studio 15 2017 Win64" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DCMAKE_EXE_LINKER_FLAGS_INIT=/LTCG -DCMAKE_SHARED_LINKER_FLAGS_INIT=/LTCG -DCMAKE_STATIC_LINKER_FLAGS_INIT=/LTCG -DCMAKE_MODULE_LINKER_FLAGS_INIT=/LTCG -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=false -DENABLE_SCRIPTING=false ..
  - C:\projects\obs-studio\CI\craftwar\cmake_64bit.cmd
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build64\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  - cd ../build32
  - cmake -E env CFLAGS="%cl_options%"  CXXFLAGS="%cl_options%" LDFLAGS="-LTCG" cmake -G "Visual Studio 15 2017" -DCMAKE_EXE_LINKER_FLAGS_INIT=/LTCG -DCMAKE_SHARED_LINKER_FLAGS_INIT=/LTCG -DCMAKE_STATIC_LINKER_FLAGS_INIT=/LTCG -DCMAKE_MODULE_LINKER_FLAGS_INIT=/LTCG -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=%D3D12_HOOK% -DENABLE_SCRIPTING=false ..
# build 32bit game capture plugin
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\plugins/win-capture/get-graphics-offsets/get-graphics-offsets.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\plugins/win-capture/graphics-hook/graphics-hook.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\plugins/win-capture/inject-helper/inject-helper.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
# package Artifact
# back to project root
  - cd ..
  - C:\projects\obs-studio\CI\before-deploy-win.cmd
  - ps: Push-AppveyorArtifact "build.7z" -FileName "OBS-git-craftwar-${env:favor_arch}.7z"
  - ps: Push-AppveyorArtifact "build64\plugins\obs-text\Release\obs-text.dll" -FileName "obs-text-${env:favor_arch}.dll"
  - set release=%APPVEYOR_REPO_COMMIT:~0,7%
#  - C:\projects\obs-studio\CI\craftwar\obs-text-blend.cmd

deploy:
  - provider: GitHub
    tag: git
    release: $(release)
#    description: $(APPVEYOR_REPO_COMMIT)
    auth_token:
      secure: KxeGOEgx0+XWdjLWDsyhC+B/w3m8zpvtVY/e+90lCLZgd/2VSuraPZDxdIPB5rfY
    force_update: true
    on:
      branch: master

test: off

cache:
  - C:\tools\vcpkg\installed\ -> appveyor.yml
  - dependencies2017.zip
  - 'VCdeps-%favor_arch%.7z'
# for blend  
  - vlc.zip
  - 'cef_binary_%CEF_VERSION%_windows64.zip'
  - Jim_OBS

#notifications:
#  - provider: Webhook
#    url:
#      secure: k1kpaz4CB5Rg5a3MTb4XKnd76fJ+9ozz5RACVnNjdgmAjA1OSssZ6LZ3g0NGfzc/
#    headers:
#      Authorization:
#        secure: A0PBwpHtsYzBOuye1EeS0fl562T0NZEInwZp0ZVER1wLQSeE6gzWGrRo2a0E7hii
