version: '{build}'
skip_tags: true
skip_commits:
  files:
    - Change.txt
    - '*.rst'
    - .travis.yml
    - 'docs/*'
    - 'craftwar.obs_updater/*'
    - '.*'
image: Visual Studio 2017
init:
  - ps: if (0) { iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1')) } #rdp debug
environment:
  CURL_VERSION: 7.55.1
  cl_options: -MP -Oi -arch:AVX2 -Gw -Gy -GL

  matrix:
    - favor_arch: AMD64
    - favor_arch: INTEL64
# setting rdp passoword never works
#  APPVEYOR_RDP_PASSWORD:
#    secure: K6XkhLVN7PZDnWWtrTKYneDPMS7FgBFYYe1xuU2s8js=

matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive plugins\win-dshow
  - git fetch --tags --prune https://github.com/obsproject/obs-studio.git # get tags from official obs
  - if exist dependencies2017.zip (curl -kLO https://obsproject.com/downloads/dependencies2017.zip -f --retry 5 -z dependencies2017.zip) else (curl -kLO https://obsproject.com/downloads/dependencies2017.zip -f --retry 5 -C -)
  #- set VCdeps_url=https://ci.appveyor.com/api/projects/craftwar_appveyor/obs-deps/artifacts/VCdeps-blend.7z?job=Environment%3A%20favor_arch%3D%favor_arch%
  - set VCdeps_url=https://github.com/craftwar/obs-deps/releases/download/git/VCdeps-%favor_arch%.7z
  - if exist VCdeps-%favor_arch%.7z (curl -kLo VCdeps-%favor_arch%.7z %VCdeps_url% -f --retry 5 -z VCdeps-%favor_arch%.7z) else (curl -kLo VCdeps-%favor_arch%.7z %VCdeps_url% -f --retry 5 -C -)

# need libcurl
  - 7z x dependencies2017.zip -oold_dep
  - 7z x VCdeps-%favor_arch%.7z -odependencies2017
  - set DepsPath32=%CD%\old_dep\win32
  - set DepsPath64=%CD%\dependencies2017\win64
  - set curlPath=%APPVEYOR_BUILD_FOLDER%\old_dep\win64\include\
  - set QTDIR32=C:\Qt\latest\msvc2015
  - set QTDIR64=C:\Qt\latest\msvc2017_64
  - set build_config=Release
  - set cl_options=%cl_options% -favor:%favor_arch%
#vcpkg
  - vcpkg remove --outdated --recurse
# /MP /Oi is default in vcpkg
  - set VCPKG_LINKER_FLAGS=/LTCG
  - set VCPKG_C_FLAGS=/arch:AVX2 /Gw /Gy /GL /favor:%favor_arch%
  - set VCPKG_CXX_FLAGS=%VCPKG_C_FLAGS%
  - vcpkg install jansson:x64-windows-static

build_script:
  - mkdir build build32 build64
  - cd ./build64
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
#  - cmd
#  - set CL=/MP /arch:AVX2 /Oi # this may not be useful (vc project doesn't respect this)
 # LDFLAGS="-LTCG" is implied with /GL
  - cmake -E env CFLAGS="%cl_options%"  CXXFLAGS="%cl_options%" LDFLAGS="-LTCG" cmake -G "Visual Studio 15 2017 Win64" -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=false -DENABLE_SCRIPTING=false ..
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build64\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  - cd ../build32
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64_x86' #use cross build x86 to speed up?
  - cmake -E env CFLAGS="%cl_options%"  CXXFLAGS="%cl_options%" LDFLAGS="-LTCG" cmake -G "Visual Studio 15 2017" -DCOPIED_DEPENDENCIES=false -DCOPY_DEPENDENCIES=true -DBUILD_CAPTIONS=true -DCOMPILE_D3D12_HOOK=false -DENABLE_SCRIPTING=false ..
#  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
# build 32bit game capture plugin
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\plugins/win-capture/get-graphics-offsets/get-graphics-offsets.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\plugins/win-capture/graphics-hook/graphics-hook.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\plugins/win-capture/inject-helper/inject-helper.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
#/t:Clean;Build #if I wana to make AVX2 as seperate build
before_deploy:
  - C:\projects\obs-studio\CI\before-deploy-win.cmd
  - ps: Push-AppveyorArtifact "build.7z" -FileName "OBS-git-craftwar-${env:favor_arch}.7z"
  - cd ..
  - ps: Push-AppveyorArtifact "build64\plugins\obs-text\Release\obs-text.dll" -FileName "obs-text-${env:favor_arch}.dll"
  - set release=%APPVEYOR_REPO_COMMIT:~0,7%

deploy:
  - provider: GitHub
    tag: git
    release: $(release)
#    description: $(APPVEYOR_REPO_COMMIT)
    auth_token:
      secure: KxeGOEgx0+XWdjLWDsyhC+B/w3m8zpvtVY/e+90lCLZgd/2VSuraPZDxdIPB5rfY
    force_update: true
    on:
      branch: master

test: off

cache:
  - C:\tools\vcpkg\installed\
  - dependencies2017.zip
  - 'VCdeps-%favor_arch%.7z'
